Repository MaximilianSoerenPollak/todotui, pull requests merged in 2023-01, with the labels that each got.

#1 README addition
  README.md
  models/tui.go
Labels: Documentaiton

#2 Add Multi-field textinput for TaskGroup title and description
  main.go
  models/tui.go
  models/tui2.go
  styles/textinputs.go
Labels: enhancement

#3 Quickfix
  models/tui.go
Labels: bug

#4 Fix: Set Values for input components to empty after pushing to list
  models/tasks.go
  models/tui.go
  types/types.go
Labels: enhancement
